<?php
//	MODE must be one of these:
//		sim:	to use the Simulator
//		test:	to use the Test System
//		live:	to use the Live System (not for debugging!)
$config['mode'] = 'sim';

//	Your VENDOR CODE, chosen when registering for SagePay
$config['vendor_name'] = '';

//	The encryption password generated by SagePay (not sure it's needed, but...)
$config['vendor_enc_pass'] = '';

//	The currency you will be using for your transactions
$config['currency'] = '';

//	Your notification URL
$config['notify'] = '';

// Timeout for curl
$config['timeout'] = 3;